### ISSUE TITLE
Database/API Setup

### ISSUE THREAD

**Issue by tylerpporter** [tylerpporter/us_farmers_market_api#2]
- [x] Create Postgres DB
    - [x] Test
    - [x] Development
- [x] Create new Rails API app 
- [x] Generate Models 
    - [x] Market
    - [x] Product
- [x] Seed from CSV
